# # Vagrant.configure("2") do |config|
# #   config.vm.box = "centos/7"
# #   config.vm.provision :shell, path: "ansibleserver.sh"
# # end

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "ansibleserver" do |ansibleserver|
    ansibleserver.vm.box = "centos/8"
    ansibleserver.vm.provision :shell, path: "ansibleserver.sh"
  end

  config.vm.define "ansibleclient" do |ansibleclient|
    ansibleclient.vm.box = "centos/8"
    ansibleclient.vm.provision :shell, path: "ansibleclient.sh"
  end

end


# Vagrant.configure("2") do |config|
#   config.vm.provision "shell", inline: "echo Hello"

#   config.vm.define "web" do |web|
#     web.vm.box = "apache"
#   end

#   config.vm.define "db" do |db|
#     db.vm.box = "mysql"
#   end
# end